# Numpy

In [2]:
import numpy as np

In [3]:
np.array?

In [5]:
arr=np.array([1,2,3,4,5])

In [6]:
print(arr)
print(type(arr))
print(np.__version__)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1.19.2


## 2 D Array

In [8]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


## 3 D Array

In [19]:
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]],dtype=float)
print(c)

[[[1. 2. 3.]
  [4. 5. 6.]
  [7. 8. 9.]]]


## d type

In [20]:
c.dtype

dtype('float64')

In [21]:
arr = np.array([1,2,3,0,0],dtype=bool)

In [22]:
arr

array([ True,  True,  True, False, False])

## Array Attribute

### ndmin

In [23]:
a1=np.array([0,1,2,3,4,5,6,7,8,9])

In [26]:
a2=np.arange(10)

In [27]:
print(a1)
print(a2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [32]:
# No of Dimension (ndim)

### Shape

In [34]:
a1.shape # ans=(row,col)

(10,)

### size of the array

In [35]:
a1.size

10

### itemsize(Size in bytes of an array item)

In [36]:
a1.itemsize

4

### dtype

In [37]:
a1.dtype

dtype('int32')

### Reshape

In [38]:
a1 = np.arange(12).reshape(3,4)

In [39]:
print(a1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Scalar operation

In [40]:
a1 + 2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [41]:
print(a1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [43]:
print(a1*2)
print()
print(a1/2)
print()
print(a1//2)
print()
print(a1**2)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]

[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]

[[0 0 1 1]
 [2 2 3 3]
 [4 4 5 5]]

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


### np.sort - view only
 - returns a sorted copy of array

In [46]:
a = np.array([2,3,45,6,7,8,9,10])
r=np.sort(a)

In [47]:
a

array([ 2,  3, 45,  6,  7,  8,  9, 10])

In [48]:
r

array([ 2,  3,  6,  7,  8,  9, 10, 45])

### np.concatenate 
     it concatenate a sequence of array along the 

In [53]:
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [55]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.nditer

In [ ]:
a=np.array([1,2,3,4,5,6,78,8,9,0,138,353,674,35423,643])
for i in np.nditer(a):
    print(i)

In [52]:
np.nditer(a)

In [57]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
b = np.array([[1,2,3],[4,5,6]])
c = np.array([[1,2],[3,4],[5,6],[7,8]],dtype=float)

In [59]:
for i in np.nditer(a):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [60]:
for i in np.nditer(b):
    print(i)

1
2
3
4
5
6


In [58]:
for i in np.nditer(c):
    print(i)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0


### np.where
 - it return the include of elements in aninput array where the given condition is satisfies

In [61]:
a = np.array([1,2,3,4,5,6,7,8,9])

In [62]:
np.where(a>50)#return index

(array([], dtype=int64),)

In [63]:
np.where(a>5)#return index

(array([5, 6, 7, 8], dtype=int64),)

### Splitting of array

- It is reverse of joining
- It breaks array into multiple arrays
- `array_split` is used with number of split as parameters to split the array

In [64]:
import numpy as np

In [69]:
arr = np.array([1,2,3,4,5,6])

In [71]:
np.array_split(arr,2)

[array([1, 2, 3]), array([4, 5, 6])]

In [72]:
np.array_split??

## Random in numpy

### randint

In [73]:
from numpy import random
x=random.randint(100)
print(x)

69


### rand

In [74]:
y = random.rand()
print(y)

0.5496940606872501


## 1 D Array

In [76]:
from numpy import random
x=random.randint(100,size=(3,5))
print(x)

[[15 38 30 60 54]
 [80 75 53 84 34]
 [47 82 46  1 23]]


In [78]:
y=random.rand(3,5)

In [80]:
print(y*100)

[[ 3.94569301 31.05295188 90.62887864 97.2135011  11.20873203]
 [70.77233989 23.48837707 68.18055981 97.04649959 66.2931453 ]
 [12.26893669 48.19389389 34.67444108 40.60605723 30.05684662]]


## Choice Method

 - It allows you to generate a random valuebased on the array

In [83]:
x = random.choice([3,5,6,7])
print(x)

3
